pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html styles.css app.js store.js config.js firebase-config.js public/
    - cp -r admin public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
